# Generated by Django 4.0 on 2022-06-22 13:44

import cloudinary.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Neighbourhood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Neighbourhood Name')),
                ('location', models.CharField(max_length=50, verbose_name='Neighbourhood Location')),
                ('occupants', models.IntegerField(null=True, verbose_name='Neighbourhood Occupants')),
                ('health_dept', models.CharField(help_text='Phone Number Format: +254722399744', max_length=16, unique=True, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,15}$')], verbose_name='Health Department Contact')),
                ('police_dept', models.CharField(help_text='Phone Number Format: +254722399744', max_length=16, unique=True, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,15}$')], verbose_name='Police Department Contact')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_photo', cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='profile_photo')),
                ('email', models.EmailField(max_length=254, null=True)),
                ('neighbourhood', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_neighbourhood', to='neighbor.neighbourhood')),
                ('profile_user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=50, null=True, verbose_name='Post Title')),
                ('post_content', models.TextField(null=True)),
                ('post_creation', models.DateTimeField(auto_now_add=True)),
                ('post_neighbourhood', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_neighbourhood', to='neighbor.neighbourhood')),
                ('post_owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=50, null=True, verbose_name='Business Name')),
                ('business_email', models.EmailField(max_length=254, null=True)),
                ('business_neighbourhood', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='neighbourhood_business', to='neighbor.neighbourhood')),
                ('business_owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
    ]
